### ISSUE TITLE
Compilation error AMALGAMSpecies.java

### ISSUE THREAD

**Issue by IgnacioVillalobosSalas** [GMUEClab/ecj#53]
When i try to compile with maven i got the following compilation errors:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[571,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[571,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[571,39] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[571,67] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[571,94] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[615,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[615,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[615,32] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[615,60] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[615,87] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[638,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[638,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[638,38] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[638,66] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[638,93] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[673,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[673,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[673,31] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[673,59] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[673,86] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[689,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[689,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[689,39] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[689,67] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[689,94] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[760,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[760,50] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[760,78] <identifier> expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[760,106] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,9] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,16] illegal start of expression
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,36] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,87] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,88] not a statement
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[798,91] ';' expected
[ERROR] /var/lib/jenkins/workspace/ECJ/ecj/src/main/java/ec/eda/amalgam/AMALGAMSpecies.java:[850,10] reached end of file while parsing
[INFO] 36 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by SigmaX** [comment]
Thanks Ignacio,

We're part-way through integrating and verifying the new amalgam package.  I've pushed a commit now that resolves the syntax errors, so you can try again.

Note that we also have failing unit tests at the moment, so if you're building a jar ("mvn package") you'll want to pass it the parameter "-Dmaven.test.skip=true".

Cheers,
Siggy

**Comment by SigmaX** [comment]
PS: if you need a version of ECJ to "just work," you might look at the stable releases here: https://cs.gmu.edu/~eclab/projects/ecj/
